version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes_from: 
      - mongo_data
  mongo_data:
    image: mongo
    volumes:
      - /data/db
    command: echo 'Data container for Auth_MongoDB'